# Generated by Django 5.1.1 on 2024-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('answer_content', models.CharField(max_length=500)),
                ('answer_timestamp', models.DateTimeField()),
                ('question_id', models.IntegerField()),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('question_content', models.CharField(max_length=500)),
                ('question_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='WebChatList',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('chat_last_timestamp', models.DateTimeField()),
                ('chat_status', models.IntegerField(default=1)),
                ('chat_deleted_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'web_chat_list',
            },
        ),
    ]
