# Generated by Django 5.1.1 on 2024-11-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_answer_chat_id_remove_answer_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webchatlist',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', default='', on_delete=django.db.models.deletion.CASCADE, to='chatbot.webchatlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question_id', default='', on_delete=django.db.models.deletion.CASCADE, to='chatbot.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', default='', on_delete=django.db.models.deletion.CASCADE, to='chatbot.webchatlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webchatlist',
            name='chat_last_timestamp',
            field=models.DateTimeField(),
        ),
    ]
