# Generated by Django 5.1.1 on 2024-10-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('average_rating', models.FloatField()),
                ('rating_number', models.IntegerField()),
                ('features', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=255)),
                ('videos', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('deleted_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'meta',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='default_profile.jpg', upload_to='profile_images/')),
                ('status', models.BooleanField(default=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
