# Generated by Django 5.1.1 on 2024-10-31 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='deleted_time',
            new_name='user_deleted_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile_image',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user',
        ),
    ]
