# Generated by Django 5.1.1 on 2024-11-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_status',
            new_name='is_active',
        ),
    ]
