# Generated by Django 5.1.1 on 2024-11-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_user_status_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='mapped_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='summarized_description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='summarized_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
