# Generated by Django 5.1.1 on 2024-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_metadata_mapped_item_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_products",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
