# Generated by Django 5.1.1 on 2024-11-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_profile_user_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="profile",
        ),
    ]
